### ISSUE TITLE
Is it fair to use GT intrinsic camera parameters in post-processing?

### ISSUE THREAD

**Issue by John6333** [mkocabas/EpipolarPose#15]
https://github.com/mkocabas/EpipolarPose/blob/9b1d316f1dc00115abe5b56ba664055a70a3a135/lib/utils/cameras.py#L64
https://github.com/mkocabas/EpipolarPose/blob/9b1d316f1dc00115abe5b56ba664055a70a3a135/lib/core/inference.py#L115
It seems that you have used the GT intrinsic parameters and GT root depth to unproject 2D to 3D.
Is it fair to claim your method is SOTA when your method uses GT camera parameters?

**Comment by mkocabas** [comment]
Dear @John6333,

We use the [Integral Pose](https://github.com/JimmySuen/integral-human-pose/) as the base model for our experiments. The evaluation function is from their [code](https://github.com/JimmySuen/integral-human-pose/blob/master/pytorch_projects/common_pytorch/dataset/hm36.py#L582). So, we can say that our results throughout the paper are fair against the baseline we use.

Regarding the fairness of overall results, unfortunately there is not a standard, official way of evaluating the performance on Human3.6M dataset. Currently, there are 2 main protocols P1 and P2 measured using the subject-9 and subject-11. However, the way people calculate these metrics differs a lot. Using GT camera parameters or not is one of them. Most of the time, the choice of using these parameters depends on the method itself. If a method is capable of predicting the scale (see [Martinez et al.](http://openaccess.thecvf.com/content_iccv_2017/html/Martinez_A_Simple_yet_ICCV_2017_paper.html) and [this issue opened by me](https://github.com/una-dinosauria/3d-pose-baseline/issues/73)) then you don't need to use GT parameters. Otherwise, as in the case of [Integral Pose](https://github.com/JimmySuen/integral-human-pose/), you would need it.

As another example to inconsistent evaluation, most of the papers have different sampling frequencies from the test set. Some uses all, some samples every 10th or 64th frames.

**Comment by mkocabas** [comment]
Closing this issue, feel free to reopen if you need.
